# Generated by Django 3.0.6 on 2020-12-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('http_code', models.CharField(blank=True, max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(blank=True, max_length=30)),
                ('timeout', models.TimeField(blank=True)),
            ],
        ),
    ]
